### ISSUE TITLE
Leverage neonctl CLI to automatically grab/create a Neon project

### ISSUE THREAD

**Issue by davidgomes** [fiberplane/create-honc-app#11]
It'd be really nice if, similarly to [neonctl's create-app command](https://neon.tech/docs/reference/cli-create-app), the `create-honc-app` leveraged `neonctl` to let users select one of their existing Neon projects _or_ create a new Neon project on the fly.

**Comment by keturiosakys** [comment]
Hey @davidgomes thanks for submitting the issue! I'd be very keen to make the `create-honc-app` more aware of the user's actual projects in Neon and automate that part of the flow.

What would be the best way to go about authenticating with Neon from the `create-honc-app` CLI? (also happy to reach out over email to go through the options here)

**Comment by davidgomes** [comment]
> Hey @davidgomes thanks for submitting the issue! I'd be very keen to make the `create-honc-app` more aware of the user's actual projects in Neon and automate that part of the flow.
> 
> What would be the best way to go about authenticating with Neon from the `create-honc-app` CLI? (also happy to reach out over email to go through the options here)

If you subshell to `neonctl auth`, it'll populate `~/.config/neonctl` with an API key that you can now use to make [Neon REST API](https://api-docs.neon.tech/reference/getting-started-with-neon-api) requests.

You can also try to implement `neonctl auth` yourself - see [its implementation here](https://github.com/neondatabase/neonctl/blob/main/src/commands/auth.ts).

**Comment by keturiosakys** [comment]
@davidgomes started working on a better setup flow for Neon in #12 :) I'm interfacing with the auth APIs directly taking inspiration from `neonctl auth`.

quick question: would it be possible to add a custom OAuth client ID (i.e. `create-honc-app`)? Currently I have to make the `create-honc-app` "pretend" that it is `neonctl` otherwise the authentication request gets rejected: https://github.com/fiberplane/create-honc-app/blob/2dec3c03df9a0fe21bd99d958920dbbcbf4c05c3/cli/src/actions/database/neon.ts#L14.

**Comment by duskpoet** [comment]
Hey! I can help with setting up the oauth client for you! Can you contact me on eduard@neon.tech please, so I can share credentials privately

**Comment by keturiosakys** [comment]
will do thanks!
